IGinX-THU/IGinX

- test/src/test/java/cn/edu/tsinghua/iginx/integration/BaseSessionConcurrencyIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/BaseSessionPoolIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/SQLSessionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/TagIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/TimePrecisionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/influxdb/InfluxDBHistoryDataCapacityExpansionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/iotdb/IoTDBHistoryDataCapacityExpansionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/parquet/ParquetHistoryDataCapacityExpansionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/rest/RestAnnotationIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/rest/RestIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/udf/TransformIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/udf/UDFIT.java
Before this change, some tests will be executed with `session.client == null`, producing lots of uninformative Null Pointer Exceptions. It takes extra efforts to find the useful error log.
After this change, errors occur during session opening, e.g. connection refused, will terminate the test and print stack trace instead of 1-line message at the top of tens of Null Pointer Exceptions' stack trace.
> Make test fail fast when cannot open session

- antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
Fix "non-fragment lexer rule ID can match the empty string" warning.
> Make lexer rule `ID` cannot match empty string

- core/src/assembly/resources/sbin/start_iginx.sh
- core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/TransformJobManager.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/udf/TransformIT.java
- test/src/test/resources/transform/transformer_sleep.py
* Make heap size computation compatible with Linux without `free` utility.
* Add heap opts into args of java to make it work.
* Unify script style and fix corner cases.
For example:
If `IGINX_HOME` contains `<space>` or `*`, `${IGINX_HOME}/path` can be corrupted by [Word Splitting](https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html) and [Filename expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html). Thus, `"${IGINX_HOME}"/path` should be used instead. With the double quote, the `{}` is absolutely redundant (It actually redundant without quote since `/` cannot be a part of variable name, but `""` make this even obvious to human without help from IDE).
* set sleep time to infinity
* add more log
* let cancel fail fast
> Fix & Refactor `start_iginx.sh` and Try fix job cancel

- tools-exportCsv/src/assembly/resources/sbin/export_csv.bat
- tools-exportCsv/src/assembly/resources/sbin/import_csv.bat
pass all the arguments of 'bat' script to the '\bin\java'
> chore(tools-exportCsv): correct the launch scripts in Windows

- conf/config.properties
- dataSources/mongodb/src/main/java/cn/edu/tsinghua/iginx/mongodb/MongoDBStorage.java
- dataSources/mongodb/src/main/java/cn/edu/tsinghua/iginx/mongodb/dummy/SchemaSample.java
这个PR实现了通过采样数据来分析文档模式的功能，来使`show columns`显示更准确的列和类型。不过，由于mongodb没有固定的模式，通过采样分析的得到的模式可能与实际查询结果有出入。
增加了对接层配置参数`schema.sample.size`，设置采样的文档数量，默认值为1000。
- 当值大于0时，通过采样分析提供dummy数据下 `show columns` 的结果；
- 否则，使用原来的方式为dummy数据显示一个大概的路径（即包含*）和固定的类型BINARY，例如db.coll.*。
> feat(mongodb): analyze schema of dummy data by sampling documents

- .github/scripts/test/cli/test_infile.sh
- .github/scripts/test/cli/test_infile_macos.sh
- .github/scripts/test/cli/test_infile_windows.sh
- .github/workflows/standalone-test.yml
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/InsertGenerator.java
- core/src/main/java/cn/edu/tsinghua/iginx/policy/Utils.java
Fix the following bug:
1. Using "LOAD DATA FROM INFILE "csvFile.csv" AS CSV SKIPPING HEADER INTO test.table(key, col1, col2, col3);" as the first command after IGinX starts, data cannot be properly inserted.
2. Making a select before the above load statement, everything is correct.
Problem:
Path list is not properly sorted for metadata generation and query.
Solution:
Sort the list
What is also added is the test to expose the corresponding problem
> fix(core): correcting the load-data-as-first-command bug

- README.md
- docs/getting_started.md
- docs/quickStarts/IGinXBySource-EnglishVersion.md
- docs/quickStarts/IGinXBySource.md
- docs/quickStarts/IGinXCluster-EnglishVersion.md
- docs/quickStarts/IGinXCluster.md
- docs/quickStarts/IGinXInOneShot-EnglishVersion.md
- docs/quickStarts/IGinXInOneShot.md
- docs/quickStarts/IGinXManual-EnglishVersion.md
- docs/quickStarts/IGinXManual.md
- docs/quickStarts_Parquet/IGinXBySource-EnglishVersion.md
- docs/quickStarts_Parquet/IGinXBySource.md
- docs/quickStarts_Parquet/IGinXCluster-EnglishVersion.md
- docs/quickStarts_Parquet/IGinXCluster.md
- docs/quickStarts_Parquet/IGinXInOneShot-EnglishVersion.md
- docs/quickStarts_Parquet/IGinXInOneShot.md
只有使用相对路径，才能在 github pages 以及本地正确跳转，否则会跳转到github仓库文件，而不是 github pages 或本地中的页面。
示例：
https://aqni.github.io/IGinX/
> docs: use relative path in Markdown document

- conf/config.properties
- dataSources/redis/src/main/java/cn/edu/tsinghua/iginx/redis/RedisStorage.java
在 `show columns` 时显示 dummy 数据。
同时，隔离 Dummy 和 IGinX 数据
- 默认使用 redis 的 database0 作为 dummy 数据源，通过 `dummy_db` 项进行配置
- 默认使用 redis 的 database1 作为 IGinX 存放数据的位置，通过 `data_db` 项进行配置
> feat(redis): show dummy columns & isolate iginx data with dummy data

- assembly/src/assembly/component/iginx-relational-driver.xml
- assembly/src/assembly/server.xml
- core/src/assembly/resources/sbin/start_iginx.bat
上次将 postgresql 改为 relational 时，没有在 assembly 模块同步修改，这次一并修改。
修复 windows 下 iginx 启动脚本，原比较方式 `if ["%half_%"] GTR ["quarter_"]` 有两个错误：
1. "quarter_" 应当改为 %quarter_%，否则比较的是字符串 `quarter_` 本身，而是不是变量 `quarter_` 的值。
2. 应当使用 `if %half_% GTR %quarter_%` 方式比较，否则会当作字符串比较，而不是数字比较。
> chore: rename postgresql to relational & compare numbers correctly in bat startup script

- core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
- core/src/main/java/cn/edu/tsinghua/iginx/metadata/utils/StorageEngineUtils.java
在22节点上添加ip为24的含有dummy_dir的文件系统，报以下错误。
```txt
dataPrefix: null
realDummyRoot: null
parameter: null
2024-05-21 23:41:42,637 [1;31mERROR[m [TThreadPoolServer WorkerProcess-0] - [org.apache.thrift.ProcessFunction.process:47] Internal error processing getBoundaryOfStorage
java.lang.NullPointerException
at java.io.File.<init>(File.java:279)
at cn.edu.tsinghua.iginx.filesystem.exec.LocalExecutor.getBoundaryOfStorage(LocalExecutor.java:355)
at cn.edu.tsinghua.iginx.filesystem.server.FileSystemWorker.getBoundaryOfStorage(FileSystemWorker.java:226)
at cn.edu.tsinghua.iginx.filesystem.thrift.FileSystemService$Processor$getBoundaryOfStorage.getResult(FileSystemService.java:495)
at cn.edu.tsinghua.iginx.filesystem.thrift.FileSystemService$Processor$getBoundaryOfStorage.getResult(FileSystemService.java: …
```
> feat(filesystem): support for redirection when adding file systems

- conf/config.properties
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/FilterPushOutJoinConditionRule.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/FunctionDistinctEliminateRule.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/InExistsDistinctEliminateRule.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/RuleCollection.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/FunctionCall.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/FunctionParams.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/GroupBy.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
实现了distinct eliminate规则，能够在保证正确性的情况下消除一些不必要的DISTINCT算子，能消除的情况如下：
1. In或EXISTS子查询中的DISTINCT
2. max或min函数中的DISTINCT
上述distinct处理是不必要的，会增加额外开销。
详细描述和测试结果见：[【PR文档】feat(optimizer): distinct eliminate rule](https://oxlh5mrwi0.feishu.cn/wiki/RhWqwNiKNiCpbok6Yxxc4XJjnph)
> feat(optimizer): distinct eliminate rule

- conf/config.properties
- dataSource/redis/src/main/java/cn/edu/tsinghua/iginx/redis/RedisStorage.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/NewSessionIT.java
- 更快的 clear data 实现：使用 flushDB 实现 clear data 操作，不逐条删除
- 将默认超时时间从 5s 改为 10s
- 重构异常与日志打印
> fix(redis): clear data timeout

- conf/config.properties
- dataSource/mongodb/src/main/java/cn/edu/tsinghua/iginx/mongodb/MongoDBStorage.java
- dataSource/redis/src/main/java/cn/edu/tsinghua/iginx/redis/RedisStorage.java
Mongodb 使用 uri 对连接参数进行详细配置，包括鉴权机制，相关语法参见 [Mongodb 文档](https://www.mongodb.com/zh-cn/docs/manual/reference/connection-string)
Redis 使用 username 和 password 两个参数配置用户名和参数，若不设置该选项，则不使用鉴权。
> 已修改用户文档
> feat(redis,mongodb): allow to authenticate

- .github/workflows/standard-test-suite.yml
- antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/FilterUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/filter/Op.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
- core/src/test/java/cn/edu/tsinghua/iginx/engine/logical/utils/LogicalFilterUtilsTest.java
- dataSource/filesystem/src/main/java/cn/edu/tsinghua/iginx/filesystem/tools/FilterTransformer.java
- dataSource/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/tools/FilterTransformer.java
- dataSource/iotdb12/src/main/java/cn/edu/tsinghua/iginx/iotdb/tools/FilterTransformer.java
- dataSource/mongodb/src/main/java/cn/edu/tsinghua/iginx/mongodb/tools/FilterUtils.java
- dataSource/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/manager/data/ProjectUtils.java
- dataSource/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/server/FilterTransformer.java
- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/meta/AbstractRelationalMeta.java
- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/meta/JDBCMeta.java
- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/meta/PostgreSQLMeta.java
- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/tools/FilterTransformer.java
- dataSource/relational/src/main/resources/mysql-meta-template.properties
- dataSource/relational/src/main/resources/oceanbase-meta.properties
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
- thrift/src/main/proto/filesystem.thrift
- thrift/src/main/proto/parquet.thrift
NotFilterRemoveRule优化器会消除所有filter中的 `not `符号，例如将 `!(a>1)` 改写为 `a<=1`，但是 `like` 没有对应的取反的比较运算符，因此新增实现 `not like`。
> feat(sql): add op "not like"

- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/RelationalStorage.java
- dataSource/relational/src/main/java/cn/edu/tsinghua/iginx/relational/query/entity/RelationQueryRowStream.java
- docs/quickStarts/IGinXManual-EnglishVersion.md
- docs/quickStarts/IGinXManual.md
- 增加RelationalStorage中HikariCP的最大连接数至20
- 将RelationalStorage中的HikariDataSource连接池的配置设置为可选参数，可在add storageengine时配置
- connection_timeout：连接超时时间，默认为30000，单位毫秒
- idle_timeout：空闲连接超时时间，默认为10000，单位毫秒
- maximum_pool_size：连接池中的最大连接数，默认为20
- minimum_idle：连接池中的最小空闲连接数，默认为1
- leak_detection_threshold：检测连接泄漏的阈值，默认为2500，单位毫秒
- prep_stmt_cache_size：SQL预编译对象缓存个数，默认为250
- prep_stmt_cache_sql_limit：SQL预编译对象缓存个数上限，默认为2048
> fix(RelationalStorage): modify HikariCP config

- core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/manager/FunctionManager.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDAF.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDF.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDSF.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/udf/python/PyUDTF.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/DropTaskStatement.java
On deleting UDFs, IGinX would remove the registration script file, remove the python interpreters from function map and done.
But all pemja interpreters would share the modules imported, making the old UDF module still valid.
On deleting UDFs, IGinX would remove the relevant module.
> fix(UDF): remove UDFs completely

- optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/ColumnPruningRule.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/UDFIT.java
修复列裁剪规则在处理udf时会丢失列的问题，并加入了一个针对udf的测试。
> fix(optimize): fix column pruning rule for UDF

- core/src/main/java/cn/edu/tsinghua/iginx/engine/StatementExecutor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/DeleteGenerator.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/DeleteStatement.java
- shared/src/main/java/cn/edu/tsinghua/iginx/constant/GlobalConstant.java
当系统中只存在只读引擎而不存在可写引擎，`clear data` 会因为找不到可操作的数据源而报错。
上述情况中，执行`delete`操作时如果发现系统中无可写引擎，则不执行删除操作，但给用户反馈警告信息。
> fix(delete): fix clear data when no writable engine exists

- dataSource/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBStorage.java
为了解决以下 PR 在测试 InfluxDB 数据源的 TPC-H 负载时，卡死在 q19 的问题：
- https://github.com/IGinX-THU/IGinX/pull/514
- https://github.com/IGinX-THU/IGinX/pull/607
InfluxDB 对接层返回的 InfluxDBQueryRowStream 持有完整的 FluxTable 对象，在消耗完毕 InfluxDBQueryRowStream 之前，FluxTable 不会得到释放。https://github.com/IGinX-THU/IGinX/pull/514 改为使用流批式的执行引擎，无法尽快释放 InfluxDBQueryRowStream 持有的 FluxTable 对象，导致 OOM 或内存不足引起的执行缓慢。
> fix(influxdb): high concurrency queries causing iginx to freeze

- .gitignore
- dependency/pom.xml
编译时如果本地已有达梦jdbc驱动的缓存，则不下载，直接使用
> fix(relational): do not install dameng jdbc driver if it exists
