- core/src/assembly/resources/sbin/start_iginx.bat
- core/src/assembly/resources/sbin/start_iginx.sh
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/storage/StorageEngineClassLoader.java
* Fix: also handle get/findResource instead of load/findClass only
* Fix: ensure JarFile closed by try-with-resources
* Refactor: simplify code
> Fix & Refactor StorageEngineClassLoader

- core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/IginxMeta.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregator.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorAvg.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorCount.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorFirst.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorLast.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorMax.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorMin.java
- core/src/main/java/cn/edu/tsinghua/iginx/rest/query/aggregator/QueryAggregatorSum.java
- example/src/main/java/cn/edu/tsinghua/iginx/session/IoTDBSessionPoolExample.java
+ Simplify ~200lines code
+ Narrow try-catch scope
+ Remove unused imports (not only REST part)
> Rest simplification 2

- docker/oneShot/build_and_run_iginx_docker.bat
- docker/onlyIginx/build_iginx_docker.bat
- docker/onlyIginx/run_iginx_docker.bat
- docs/quickStarts/IGinXByDocker-EnglishVersion.md
- docs/quickStarts/IGinXByDocker.md
- docs/quickStarts/IGinXBySource-EnglishVersion.md
- docs/quickStarts/IGinXBySource.md
- docs/quickStarts/IGinXCluster-EnglishVersion.md
- docs/quickStarts/IGinXCluster.md
- docs/quickStarts/IGinXInOneShot-EnglishVersion.md
- docs/quickStarts/IGinXInOneShot.md
源码无修改，部署打包时需要修改根目录下的runIGinXOn1Host.bat，将文件中路径字符串内的\"/\"改为\"\\\"以兼容Windows10（注：仅需修改双引号内的路径，双引号外无需修改）
- 添加安装Node.js的提示和步骤引导
- 删除不必要的编译命令
- 更新IGinX编译成功时的提示信息
- 更新OneShot、OnlyIGinX镜像构建成功时的提示信息
- 添加构建OneShot镜像的bat文件（适用于Windows场景）
- 添加构建OnlyIGinX镜像、运行该镜像的bat文件（适用于Windows场景）
- 将OnlyIGinX镜像构建的参数调整提示前移
- 修改错误的配置参数
> 测试并修改完善了项目启动文档

- .github/actions/confWriter/action.yml
- .github/scripts/dataSources/influxdb.sh
- .github/scripts/dataSources/influxdb_macos.sh
- .github/workflows/standalone-test-pushdown.yml
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/FilterPushDownOptimizer.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/ExprUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/OperatorUtils.java
- dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/InfluxDBStorage.java
- dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/query/entity/InfluxDBHistoryQueryRowStream.java
- dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/query/entity/InfluxDBQueryRowStream.java
- dataSources/influxdb/src/main/java/cn/edu/tsinghua/iginx/influxdb/tools/FilterTransformer.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
Query and dummy query with predicate pushdown are implemented
> feat(InfluxDB): select pushdown for InfluxDB

- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/FilterFragmentOptimizer.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
The filter fragment optimizer now behaves correctly with sub query and query with JOIN
> hotfix(optimizer): fix filter fragment optimizer

- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/OperatorUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
非关联子查询支持Top-N查询（同时使用order by和limit）。
> fix subquery

- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/utils/ExprUtils.java
- dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/tools/DataViewWrapper.java
- dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/tools/TagKVUtils.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/PostgreSQLStorage.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/query/entity/PostgreSQLQueryRowStream.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/Constants.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/FilterTransformer.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/PostgreSQLSchema.java
- dataSources/postgresql/src/main/java/cn/edu/tsinghua/iginx/postgresql/tools/TagKVUtils.java
- dataSources/timescaledb/src/main/java/cn/edu/tsinghua/iginx/timescaledb/TimescaleDBStorage.java
- shared/src/main/java/cn/edu/tsinghua/iginx/constant/GlobalConstant.java
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/StringUtils.java
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/TagKVUtils.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/postgresql/PostgreSQLHistoryDataGenerator.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
* Now the separator of postgresql has been changed. 
* Now the TagKV Separator has been changed from Chinese Character to ASCII Character.
> hotfix(postgresql): change separator

- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/RemoveNotRule.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/optimizer/rules/RuleCollection.java
- core/src/test/java/cn/edu/tsinghua/iginx/optimizer/RBOTest.java
- core/src/test/java/cn/edu/tsinghua/iginx/optimizer/TreeBuilder.java
> feat(optimizer): add remove_not rule

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter.java
修复了zeppelin中cancel按钮会直接关闭session，导致后续查询无法进行的问题。
> hotfix(zeppelin): fix zeppelin cancel

- test/pom.xml
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/parquet/ParquetHistoryDataGenerator.java
在扩容测试中直接使用 parquet-file 依赖项生成历史数据，而不是调用IGinX的Paruqet对接层相关代码
> refactor(parquet): generator history data without using cn.edu.tsinghua:parquet

- core/src/main/resources/log4j2.properties
日志文件滚动创建，满足下列条件之一：
- 日志文件尺寸达到100MiB
- 新的一天
- 重新启动
触发操作：
1. 创建一个新的日志文件
2. 将旧日志文件压缩，按日期和编号重命名
最多存在30个日志文件
> chore(log): write log into rolling file

- session_py/iginx/iginx_pyclient/dataset.py
- session_py/iginx/iginx_pyclient/session.py
- session_py/iginx/iginx_pyclient/utils/byte_utils.py
python session could not process None when exporting table to stream.
use bitmap to skip None value
> fix(pysession): fix export as stream

- .github/workflows/standalone-test-pushdown.yml
Removing redundant tests on Parquet
> fix(test): remove unnecessary test on Parquet

- core/src/assembly/resources/sbin/start_iginx.bat
- core/src/assembly/resources/sbin/start_iginx.sh
- dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/db/lsm/OneTierDB.java
- dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/io/parquet/IParquetWriter.java
- dataSources/parquet/src/main/java/cn/edu/tsinghua/iginx/parquet/util/StorageProperties.java
> fix(parquet): limit buffer size

- client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
> fix(client): remove duplicated key header

- .github/workflows/DB-CE.yml
- .github/workflows/case-regression.yml
- .github/workflows/full-test-suite.yml
- .github/workflows/standalone-test-pushdown.yml
- .github/workflows/standalone-test.yml
- .github/workflows/standard-test-suite.yml
- .github/workflows/unit-mds.yml
- .github/workflows/unit-test.yml
标准测试套件（standard-test-suite.yml）运行过去使用的一系列 CI 中的测试，提PR时触发。
完整测试套件（full-test-suite.yml）额外测试 etcd 下的各种 CI 中的测试，每周日触发。
> ci: create different test suites

- .github/workflows/remote-test.yml
Decrease test amount by testing representitive databases only.
> test(ci): remove some tests

- conf/config.properties
- core/pom.xml
- core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
- core/src/main/java/cn/edu/tsinghua/iginx/notice/EmailNotifier.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/JobRunner.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/TransformJobManager.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/pojo/Job.java
- core/src/test/java/cn/edu/tsinghua/iginx/notice/EmailNotifierTest.java
- pom.xml
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
详见文档：
https://oxlh5mrwi0.feishu.cn/docx/WNmXdqQWNoG6ZFxqOmbcXZwpnYX?from=from_copylink
> feat(core): notify user by email after Transform Job finished or failed

- .github/actions/confWriter/action.yml
- .github/actions/context/action.yml
- .github/actions/iginxRunner/action.yml
- .github/scripts/iginx/iginx_udf_path.sh
- .github/scripts/test/cli/test_infile.sh
- .github/scripts/test/cli/test_infile_macos.sh
- .github/scripts/test/cli/test_infile_windows.sh
- .github/scripts/test/cli/test_outfile.sh
- .github/scripts/test/cli/test_outfile_macos.sh
- .github/scripts/test/cli/test_outfile_windows.sh
- .github/scripts/test/cli/test_py_register.sh
- .github/scripts/test/cli/test_py_register_macos.sh
- .github/scripts/test/cli/test_py_register_windows.sh
- .github/workflows/standalone-test.yml
- test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/BaseCapacityExpansionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/session/NewSessionIT.java
> feat(test): remove version dependencies from the test path

- udf_funcs/python_scripts/udf_max.py
Correct an incorrect variable name in `max` udf function.
> fix(udf): correct variable names in udf

- assembly/src/assembly/resources/zookeeper/conf/zoo.cfg
- docs/quickStarts_Parquet/IGinXInOneShot.md
> fix(assembly): disable zookeeper admin server to avoid bind 8080 port

- .github/actions/dependence/action.yml
- .github/workflows/DB-CE.yml
- .github/workflows/assembly-test.yml
- .github/workflows/case-regression.yml
- .github/workflows/codeql.yml
- .github/workflows/remote-test.yml
- .github/workflows/standalone-test-pushdown.yml
- .github/workflows/standalone-test.yml
- .github/workflows/standard-test-suite.yml
- .github/workflows/tpc-h.yml
- .github/workflows/unit-mds.yml
- .github/workflows/unit-test.yml
change macos-13 to macos-latest
> test(ci): change to macos-latest

- core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
> fix(sql): fix upper case system function in having

- client/src/main/java/cn/edu/tsinghua/iginx/client/IginxClient.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/StatementExecutor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/pipeline/Projector.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/BatchSchemaUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/task/AbstractPhysicalTask.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/Result.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Batch.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/BatchSchema.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/NaivePhysicalExecutorFactory.java
- session/src/main/java/cn/edu/tsinghua/iginx/session/SessionExecuteSqlResult.java
- shared/pom.xml
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/ByteUtils.java
- thrift/src/main/proto/rpc.thrift
- 实现物理算子Projector（对应逻辑算子Project & Reorder & Rename & AddSchemaprefix）
- 改造没有fetchsize的SQL session接口
> feat(core): impl Projector && modify some session

- antlr/src/main/antlr4/cn/edu/tsinghua/iginx/sql/Sql.g4
- core/src/main/java/cn/edu/tsinghua/iginx/engine/logical/generator/QueryGenerator.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/naive/NaiveOperatorMemoryExecutor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/AddSequenceLazyStream.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/stream/StreamOperatorMemoryExecutor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/ExprUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/utils/RowUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Header.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/data/read/Row.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/expr/ExpressionVisitor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/expr/KeyExpression.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/expr/SequenceExpression.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/function/system/utils/ValueUtils.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/AddSequence.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/shared/operator/type/OperatorType.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/IginXSqlVisitor.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/select/SelectStatement.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/select/UnarySelectStatement.java
- core/src/main/java/cn/edu/tsinghua/iginx/sql/statement/select/subclause/SelectClause.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/ColumnPruningRule.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownAddSchemaPrefixRule.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownRenameRule.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/logical/optimizer/rules/FilterPushDownTransformRule.java
- session/src/main/java/cn/edu/tsinghua/iginx/session/SessionExecuteSqlResult.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
1. 增加生成自增列的语法
2. 增加KEY列的操作语法，包括：将特定列升级成KEY列，将KEY列降级成普通列
详见https://oxlh5mrwi0.feishu.cn/docx/Gd8pd1aMDoNMIexXBPJcaea6n0g
> feat(sql): auto increment sequence & alter key

- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/JoinHashMap.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/executor/binary/stateful/StatefulBinaryExecutor.java
limit
part of hash-join
fetch-all task
> fix(arrow): fix last PR

- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/ConditionJoinCollection.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/CrossJoinList.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/JoinCursor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/JoinHashMap.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/JoinOption.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/compute/join/JoinOutputBuffer.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/memory/execute/executor/binary/stateful/HashJoinExecutor.java
- core/src/main/java/cn/edu/tsinghua/iginx/engine/physical/task/BinarySinkMemoryPhysicalTask.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/NaivePhysicalPlanner.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/initializer/FilterInfoGenerator.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/initializer/MarkJoinInfoGenerator.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/initializer/TransformProjectionInfoGenerator.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/util/Expressions.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/util/Filters.java
- optimizer/src/main/java/cn/edu/tsinghua/iginx/physical/optimizer/naive/util/HashJoins.java
markjoin of hashjoin
other filter of hashjoin
> feat(arrow): impl TPC-H q4

- .github/workflows/release.yml
> ci: auto rename released package

- test/src/test/resources/tpch/queries/q17.sql
- test/src/test/resources/tpch/queries/q2.sql
- test/src/test/resources/tpch/queries/q20.sql
- test/src/test/resources/tpch/queries/q7.sql
- test/src/test/resources/tpch/queries/q8.sql
- test/src/test/resources/tpch/queries/q9.sql
使用 cte 代替临时表，使用内置 extract 函数代替 extractYear UDF。
> test: remove temp tables and udf in tpc-h test

- conf/config.properties
- core/pom.xml
- core/src/main/java/cn/edu/tsinghua/iginx/conf/Config.java
- core/src/main/java/cn/edu/tsinghua/iginx/conf/ConfigDescriptor.java
- core/src/main/java/cn/edu/tsinghua/iginx/notice/EmailNotifier.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/JobValidationChecker.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/exec/TransformJobManager.java
- core/src/main/java/cn/edu/tsinghua/iginx/transform/pojo/Job.java
- core/src/test/java/cn/edu/tsinghua/iginx/notice/EmailNotifierTest.java
- pom.xml
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/EmailFromYAML.java
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/JobFromYAML.java
- shared/src/main/java/cn/edu/tsinghua/iginx/utils/NotificationFromYAML.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/sql/SQLSessionIT.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/TransformIT.java
- test/src/test/resources/transform/TransformSingleSqlStatementWithEmail.yaml
已修改用户手册
增加了一个测试来验证通知
本地使用QQ邮箱进行了验证
> feat(transform): email notification configured by YAML

- core/src/test/java/cn/edu/tsinghua/iginx/notice/EmailNotifierTest.java
- test/src/test/java/cn/edu/tsinghua/iginx/integration/func/udf/TransformIT.java
email有时未能收到邮件，这里在测试中增加一个等待，确保邮件投递到邮箱
> test: make email-test more robust

- .github/actions/setup/mysql/action.yml
- .github/workflows/standard-test-suite.yml
- dataSource/vectordb/pom.xml
- Maven 构建失败，jar 依赖版本冲突
- https://github.com/IGinX-THU/IGinX/actions/runs/13230165532/job/37074564917
- Mysql 下载失败，显示 http 403
- https://github.com/IGinX-THU/IGinX/actions/runs/13230165532/job/37074663432
- 禁用 macos 上的 vectordb 测试
> fix: recent CI failure

- client/src/assembly/resources/sbin/start_cli.bat
- client/src/assembly/resources/sbin/start_cli.sh
> fix(client): fix client Chinese character encoding issue
